server:
  port: 7777
  servlet:
    path: /eureka_server1
spring:
  application:
    name: /eureka_server1

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:7777/eureka1
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找